name: Nix Flake actions

on:
  push:
    tags:
      - "dev_release"

permissions:
  contents: write

jobs:
  build-linux:
    name: Upload linux binary
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Build release
        run: |
          cargo build --release --no-default-features
      - name: Prepare release
        run: |
          chmod +x target/release/aoe
          mv target/release/aoe .
      - name: Bundle release
        run: |
          tar -czf aoe_linux.tar.gz aoe assets
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aoe_linux.tar.gz
          asset_name: aoe_linux.tar.gz
          tag: "dev"
          overwrite: true
  build-windows:
    name: Upload windows binary
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Build
        id: set-matrix
        run: nix develop -c cargo zigbuild --target=x86_64-pc-windows-gnu --no-default-features --release
      - name: Prepare release
        run: |
          mkdir target/x86_64-pc-windows-gnu/release/assets && cp -r assets target/x86_64-pc-windows-gnu/release/assets
      - name: Zip release
        uses: vimtor/action-zip@v1.1
        with:
          files: target/x86_64-pc-windows-gnu/release/assets target/x86_64-pc-windows-gnu/release/aoe.exe
          dest: aoe_windows.zip
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aoe_windows.zip
          asset_name: aoe_windows.zip
          tag: "dev"
          overwrite: true
