name: Nix Flake actions

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  build:
    name: Upload windows binary
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Build
        id: set-matrix
        run: nix develop -c cargo zigbuild --target=x86_64-pc-windows-gnu --no-default-features --release
      - name: Prepare release
        run: |
          mkdir target/x86_64-pc-windows-gnu/release/assets && cp -r assets target/x86_64-pc-windows-gnu/release/assets
      - name: Zip release
        uses: vimtor/action-zip@v1.1
        with:
          files: target/x86_64-pc-windows-gnu/release/assets target/x86_64-pc-windows-gnu/release/aoe.exe
          dest: aoe_windows.zip
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aoe_windows.zip
          asset_name: aoe_windows.zip
          tag: "0.1"
          overwrite: true
